package io.github.codetoil.tothestars.asm;

import com.google.common.eventbus.EventBus;
import net.minecraftforge.fml.common.DummyModContainer;
import net.minecraftforge.fml.common.LoadController;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.relauncher.IFMLLoadingPlugin.MCVersion;

import java.util.Collections;

@MCVersion("1.12.2")
public class TTSModContainer extends DummyModContainer
{
	public TTSModContainer()
	{
		super(new ModMetadata());
		ModMetadata meta = this.getMetadata();
		meta.modId = "tothestars";
		meta.name = "To The Stars";
		meta.version = "0.1.1";
		meta.description = "Allows you to travel to stars in galacticraft";
		meta.authorList = Collections.singletonList("Codetoil");
		meta.url = "";
		meta.autogenerated = false;
	}
	
	@Override
	public boolean registerBus(EventBus bus, LoadController controller)
	{
		bus.register(this);
		return true;
	}
}
