package io.codetoil.tothestars.asm;

import com.google.common.collect.Lists;
import com.google.common.eventbus.EventBus;
import net.minecraftforge.fml.common.DummyModContainer;
import net.minecraftforge.fml.common.LoadController;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.versioning.ArtifactVersion;
import net.minecraftforge.fml.common.versioning.DefaultArtifactVersion;
import net.minecraftforge.fml.relauncher.IFMLLoadingPlugin.MCVersion;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;

@MCVersion("1.12.2")
public class TTSModContainer extends DummyModContainer
{
	public TTSModContainer()
	{
		super(new ModMetadata());
		ModMetadata meta = this.getMetadata();
		meta.modId = "tothestarscore";
		meta.name = "ToTheStars Core";
		meta.version = "1.1.2";
		meta.description = "The coremod for ToTheStars";
		meta.authorList = Collections.singletonList("Codetoil");
		meta.url = "";
		meta.autogenerated = false;
	}
	
	@Override
	public boolean registerBus(EventBus bus, LoadController controller)
	{
		bus.register(this);
		return true;
	}
}
